removed files 10-dhcp-config & 99-default, because they are not neede…
RHsyseng/rhcos-slb pull request #7
Opened 2021-03-31 20:33 UTC by kobi86

…d, they are being created in the custome-config file

Some order in the Repo :)

2021-03-31 20:52 UTC, kobi86 commented
@phoracek this is what you wanted ? PR that will include some cleanup and the fix? 
or you want to do it with two different PRs?

2021-04-01 10:52 UTC, phoracek requested changes
Some nits, but overall looks well. Commented on diffs.

By splitting to commits what I mean was - if you are moving and changing a file, move it in one commit and change in another to allow for a clear diff.

I won't fight against redundant file cleanup in this PR. As long as it does not bring risk of regressions and does not make the actual bugfix harder to review.

2021-04-01 10:52 UTC, phoracek commented on custom-config.fcc
> +        WantedBy=coreos-installer.target
This is missing the last EOL

2021-04-01 10:52 UTC, phoracek commented on 10-dhcp-config.conf
> -[main]
Please format the commit message. The title line should be under 70 characters. The rest should be divided in a paragraph bellow. You can see it here that even GitHub gets confused by the long line and it does not help readability of the log.

You say that these files just get created. Is there any guidance on how to create them? Is it just a regular process while working with RHCOS and we assume folks know how to generate it?

2021-04-01 10:52 UTC, phoracek commented on custom-config.fcc
> +        After=coreos-installer.service
Would you please comment on this change in the commit message?

2021-04-05 07:21 UTC, closed without merging